stages:
  - lint
  - test
  - build
  - publish

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  ARTIFACTS_ANDROID: "./app/build"

.base_job:
  before_script:
    - set -euxo pipefail
    - brew install openjdk@17
    - export JAVA_HOME=$(brew --prefix openjdk@17)
  tags:
    - android_sdk_30

lint/kmp:
  extends: .base_job
  stage: lint
  script:
    - cd kmp
    - ./gradlew lint

test/kmp:
    extends: .base_job
    stage: test
    script:
        - cd kmp
        - ./gradlew test

build/kmp:
  extends: .base_job
  stage: build
  script:
    - cd kmp
    - ./gradlew :redux:assemble

publish/library:
  extends: .base_job
  stage: publish
  script:
    - cd kmp
    - ./gradlew publishToMavenCentral --no-configuration-cache
  when: manual

